In [39]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [40]:
data = pd.read_csv('https://covid.ourworldindata.org/data/owid-covid-data.csv')

In [41]:
df = data[data.location=='India']

In [42]:
df1 = df.copy()

In [43]:
for i in range(len(df1['tests_units'])):
    print(type(df1['tests_units'].iloc[i]))

<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'float'>
<class 'float'>

In [46]:
for i in range(len(df1['tests_units'])):
    df1['tests_units'].iloc[i] = str(df1['tests_units'].iloc[i])
    print(type(df1['tests_units'].iloc[i]))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

C:\Users\Admin\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

In [47]:
def impute_mean(df):
    for i in df.columns:
        if (df[i].dtype == 'float64') | (df[i].dtype == 'int64'):
            df[i].fillna(df[i].mean(),inplace =True)
def impute_mode(df):
    for i in df.columns:
        if (df[i].dtype == 'object'):
            df[i].fillna(df[i].mode(),inplace =True)

In [48]:
impute_mean(df1)
impute_mode(df1)

In [49]:
for i in df1.columns:
    print((df1[i].isnull().sum()))

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0

In [50]:
import datetime as dt
df1["date"]=pd.to_datetime(df1["date"])
df1["date"]=df1["date"].map(dt.datetime.toordinal)

In [76]:
rem_cols = []
for i in df1.columns:
#     print(df1[i].dtype)
    if df1[i].dtype == 'object':
        rem_cols.append(i)
df1.drop(rem_cols,axis=1,inplace = True)

In [84]:
X = df1.drop('total_cases', axis='columns')
X

,date,new_cases,total_deaths,new_deaths,total_cases_per_million,new_cases_per_million,total_deaths_per_million,new_deaths_per_million,total_tests,new_tests,...,aged_70_older,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy
13249,737424,0.0,0.0,0.0,0.000,0.000,0.000,0.000,4.005175e+06,123035.864865,...,3.414,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66
13250,737425,0.0,0.0,0.0,0.000,0.000,0.000,0.000,4.005175e+06,123035.864865,...,3.414,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66
13251,737426,0.0,0.0,0.0,0.000,0.000,0.000,0.000,4.005175e+06,123035.864865,...,3.414,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66
13252,737427,0.0,0.0,0.0,0.000,0.000,0.000,0.000,4.005175e+06,123035.864865,...,3.414,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66
13253,737428,0.0,0.0,0.0,0.000,0.000,0.000,0.000,4.005175e+06,123035.864865,...,3.414,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13447,737623,34956.0,25602.0,687.0,727.412,25.330,18.552,0.498,1.307272e+07,333228.000000,...,3.414,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66
13448,737624,34884.0,26273.0,671.0,752.690,25.278,19.038,0.486,1.343374e+07,361024.000000,...,3.414,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66
13449,737625,38902.0,26816.0,543.0,780.880,28.190,19.432,0.393,1.379187e+07,358127.000000,...,3.414,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66
13450,737626,40425.0,27497.0,681.0,810.174,29.293,19.925,0.493,4.005175e+06,123035.864865,...,3.414,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66
13451,737627,37148.0,28084.0,587.0,837.092,26.919,20.351,0.425,4.005175e+06,123035.864865,...,3.414,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66

In [83]:
y = df1.total_cases
y

13249          0.0
13250          0.0
13251          0.0
13252          0.0
13253          0.0
           ...
13447    1003832.0
13448    1038716.0
13449    1077618.0
13450    1118043.0
13451    1155191.0
Name: total_cases, Length: 203, dtype: float64

In [121]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [122]:
from sklearn.ensemble import RandomForestRegressor
regr = RandomForestRegressor(n_estimators = 1000, max_depth=2, random_state=0)
regr.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=2, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=1000, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

In [123]:
model.score(X_test, y_test)

0.7804878048780488

In [124]:
y_pred=model.predict(X_test)

In [125]:
y_pred

array([7.424170e+05, 0.000000e+00, 3.000000e+00, 6.412000e+03,
       1.000000e+00, 3.089930e+05, 3.200000e+02, 8.209160e+05,
       1.650000e+02, 2.450600e+04, 3.000000e+00, 2.765830e+05,
       2.366570e+05, 3.000000e+00, 3.669460e+05, 1.000000e+00,
       3.000000e+00, 4.939100e+04, 0.000000e+00, 1.517670e+05,
       1.910000e+02, 8.209160e+05, 2.450600e+04, 1.910000e+02,
       3.000000e+00, 1.118043e+06, 0.000000e+00, 6.046410e+05,
       0.000000e+00, 1.067500e+05, 5.966200e+04, 3.000000e+00,
       1.583330e+05, 4.904010e+05, 7.938020e+05, 3.000000e+00,
       4.390000e+02, 0.000000e+00, 7.424170e+05, 6.000000e+00,
       1.338700e+04])

In [127]:
 y_test

13439     767296.0
13262          0.0
13306          3.0
13348       5734.0
13280          1.0
13413     308993.0
13333        562.0
13442     849553.0
13327        165.0
13363      23077.0
13305          3.0
13409     266598.0
13406     236657.0
13311          3.0
13419     380532.0
13279          1.0
13303          3.0
13375      49391.0
13258          0.0
13396     151767.0
13329        231.0
13441     820916.0
13364      24506.0
13328        191.0
13298          3.0
13450    1118043.0
13266          0.0
13432     604641.0
13252          0.0
13389     106750.0
13378      59662.0
13310          3.0
13397     158333.0
13427     508953.0
13440     793802.0
13290          3.0
13331        439.0
13256          0.0
13438     742417.0
13313          6.0
13356      13387.0
Name: total_cases, dtype: float64

In [130]:
model.predict([[13356]])

ValueError: Number of features of the model must match the input. Model n_features is 29 and input n_features is 1

In [132]:
X_test.columns

Index(['date', 'new_cases', 'total_deaths', 'new_deaths',
       'total_cases_per_million', 'new_cases_per_million',
       'total_deaths_per_million', 'new_deaths_per_million', 'total_tests',
       'new_tests', 'total_tests_per_thousand', 'new_tests_per_thousand',
       'new_tests_smoothed', 'new_tests_smoothed_per_thousand',
       'stringency_index', 'population', 'population_density', 'median_age',
       'aged_65_older', 'aged_70_older', 'gdp_per_capita', 'extreme_poverty',
       'cardiovasc_death_rate', 'diabetes_prevalence', 'female_smokers',
       'male_smokers', 'handwashing_facilities', 'hospital_beds_per_thousand',
       'life_expectancy'],
      dtype='object')